"""empty message

Revision ID: 48b6b15ecde8
Revises: 3daa162baf1e
Create Date: 2022-04-17 18:24:36.052204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b6b15ecde8'
down_revision = '3daa162baf1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('status', sa.Enum('ATIVO', 'CANCELADO', name='status'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'status')
    # ### end Alembic commands ###
