"""empty message

Revision ID: 5fbab2eaff82
Revises: 48b6b15ecde8
Create Date: 2022-04-24 17:13:12.821049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbab2eaff82'
down_revision = '48b6b15ecde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('total_price', sa.REAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'total_price')
    # ### end Alembic commands ###
