"""empty message

Revision ID: e43b3d957da6
Revises: 5fbab2eaff82
Create Date: 2022-04-24 18:23:31.813826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43b3d957da6'
down_revision = '5fbab2eaff82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Rooms', sa.Column('short_description', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Rooms', 'short_description')
    # ### end Alembic commands ###
